FROM node:lts-alpine

WORKDIR /usr/src/gmc.sh
COPY ./package*.json ./
RUN npm install
COPY ./lerna.json ./lerna.json
COPY ./src/web ./src/web
COPY ./src/shared ./src/shared
RUN npm run clean-install
WORKDIR /usr/src/gmc.sh/src/web
RUN npm run build

EXPOSE 3000

CMD [ "npm", "run", "start" ]