FROM node:lts

WORKDIR /usr/src/gmc.sh
COPY ./package*.json ./
RUN npm install
COPY ./lerna.json ./lerna.json
COPY ./src/core-api ./src/core-api
COPY ./src/shared ./src/shared

RUN apt-get install -y autoconf libtool

RUN npm run clean-install
WORKDIR /usr/src/gmc.sh/src/core-api

ENV NODE_ENV=production
EXPOSE 80

CMD [ "npm", "run", "start" ]