CREATE TABLE IF NOT EXISTS "User" (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255),
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS "Url" (
  id SERIAL PRIMARY KEY NOT NULL,
  shortened VARCHAR(20) NOT NULL,
  target TEXT NOT NULL,
  "userId" INTEGER NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  FOREIGN KEY ("userId") REFERENCES "User"(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Session" (
  id SERIAL PRIMARY KEY NOT NULL,
  "sessionId" VARCHAR(20) NOT NULL UNIQUE,
  "userId" INTEGER NOT NULL,
  duration INTEGER NOT NULL DEFAULT 30,
  "issuedAt" TIMESTAMP NOT NULL DEFAULT now(),
  FOREIGN KEY ("userId") REFERENCES "User"(id) ON DELETE CASCADE
);