CREATE TABLE IF NOT EXISTS "User" (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255),
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now()
);
CREATE TABLE "Url" (
  id SERIAL PRIMARY KEY NOT NULL,
  shortened VARCHAR(20) NOT NULL,
  target TEXT NOT NULL,
  "userId" INTEGER NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  FOREIGN KEY ("userId") REFERENCES "User"(id) ON DELETE CASCADE
);