CREATE TABLE "Url" (
  id VARCHAR(255) PRIMARY KEY NOT NULL,
  url VARCHAR(255) UNIQUE NOT NULL,
  target TEXT NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  "userId" VARCHAR(255) NOT NULL,
  "timesVisited" BIGINT NOT NULL DEFAULT 0,
  FOREIGN KEY ("userId") REFERENCES "User"(id) ON DELETE CASCADE
)